apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml

# Uncomment and modify this section to set the image name and tag
# images:
# - name: meds-bot
#   newName: your-registry/meds-bot
#   newTag: latest