apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meds-bot-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # This is the default storage class in k3s